### ISSUE TITLE
build issue encountered on NERSC Perlmutter/Cori

### ISSUE THREAD

**Issue by whannah1** [ClimateGlobalChange/squadgen#4]
I needed to rebuild squadgen on Perlmutter and ran into a few build issues.

first error:
`make[1]: *** No rule to make target '/usr/include/bits/byteswap-16.h', needed by 'depend/netcdf.d'.  Stop.`

I noticed that the file `/usr/include/bits/byteswap.h` actually exists, so I edited these two files accordingly:

- src/depend/netcdf.d
- src/depend/lodepng.d

Then I got this error:
`make[1]: *** No rule to make target '/usr/include/libio.h', needed by 'depend/lodepng.d'.  Stop.`

This appears to have been deprecated, so I deleted `/usr/include/libio.h` from `src/depend/lodepng.d`

next up:
`make[1]: *** No rule to make target '/usr/include/_G_config.h', needed by 'depend/lodepng.d'.  Stop.`

this file also doesn't seem to exist anywhere, so I just tried deleting it from the list.

After those changes the build started to work, but then ended with a bunch of errors like:
` undefined reference to `std::__throw_bad_array_new_length()'`

Not sure how to fix this, help!

**Comment by paullric** [comment]
I did the following:

module load cray-hdf5
module load cray-netcdf

then changed src/Makefile to:

# NETCDF library directories
NETCDF_INCLUDEDIR=$(NETCDF_DIR)/include
NETCDF_LIBDIR=$(NETCDF_DIR)/lib

That seemed to build without issue.

/global/homes/p/paullric/pm/squadgen/SQuadGen

**Comment by whannah1** [comment]
ah ok, seems ot be working now, thanks!
