### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by xylar** [ClimateGlobalChange/squadgen#5]
@paullric, would you be willing to make a new release of this package?  If you do that, I can make a conda package of it and include it in E3SM-Unified that way.  Right now, I'm doing something a lot less official.

**Comment by xylar** [comment]
@paullric, one more request: Could you add a license?  We can't put squadgen on conda-forge without one.

**Comment by paullric** [comment]
@xylar Should be done now in v1.2.1

**Comment by xylar** [comment]
Wonderful, I really appreciate it!

**Comment by xylar** [comment]
@paullric, thanks so much for taking care of these things.  SQuadGen is now available as a conda package from https://github.com/conda-forge/squadgen-feedstock.

If someone installs [miniforge3](https://github.com/conda-forge/miniforge?tab=readme-ov-file#miniforge3), they can install it into a conda environment with:
```
conda install squadgen
```

**Comment by paullric** [comment]
Great!  Could you add a PR which details the installation information?

**Comment by xylar** [comment]
Yes, I'll be glad to do that as soon as I can find a little time.
